[package]
name = "voxel"
version = "0.1.0"
edition = "2021"

[dependencies]
gfx = {path = "../gfx"}
game = {path = "../game"}
util = {path = "../util" }
bytemuck = { version = "1.14.1", features = [ "derive" ] }
log = { version = "0.4.20", features = ["std"]}