[package]
name = "voxel"
version = "0.1.0"
edition = "2021"

[dependencies]
gfx      = { workspace = true }
util     = { workspace = true }
bytemuck = { workspace = true }
log      = { workspace = true }