[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log = { version = "0.4.20", features = ["std"]}
winit = "0.29"
wgpu = "0.19"
pollster = "0.3.0"
bytemuck = { version = "1.14.1", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
strum = {version = "0.26", features = ["derive"] }
nalgebra-glm = {version = "0.18.0", features = ["convert-bytemuck"] }
