[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

[workspace]
members = ["crates/util", "crates/gfx", "crates/game", "crates/voxel", "crates/verdigris"]

[dependencies]
util      = { workspace = true }
gfx       = { workspace = true }
game      = { workspace = true }
voxel     = { workspace = true }
verdigris = { workspace = true }
log       = { workspace = true }

[workspace.dependencies]
util = { path = "crates/util" }
gfx = { path = "crates/gfx" }
game = { path = "crates/game" }
voxel = { path = "crates/voxel" }
verdigris = { path = "crates/verdigris" }
log = { version = "0.4.20", features = ["std"] }
bytemuck = { version = "1.14.1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = [
    "png",
    "jpeg",
] }
tobj = "4.0.1"
itertools = "0.12.1"
noise = "0.8.2"
rand = "0.8.5"
rayon = "1.8.1"

[profile.dev]
opt-level = 2
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true

[profile.release]
debug = true

[profile.deploy]
inherits = "release"
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = true
panic = "unwind"
incremental = true
codegen-units = 1
rpath = true
