[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

[workspace]
members = ["crates/util", "crates/gfx", "crates/game", "crates/voxel"]

[dependencies]
util = { path = "crates/util" }
gfx = { path = "crates/gfx" }
game = { path = "crates/game" }
log = { version = "0.4.20", features = ["std"] }
voxel = { path = "crates/voxel" }
bytemuck = { version = "1.14.1", features = ["derive"] }
image = { version = "0.24", default-features = false, features = [
    "png",
    "jpeg",
] }
tobj = "4.0.1"
itertools = "0.12.1"
noise = "0.8.2"
human_bytes = "0.4.3"
rand = "0.8.5"

[profile.dev]
opt-level = 3
debug = true
debug-assertions = true
overflow-checks = true
lto = false
panic = "unwind"
incremental = true

[profile.deploy]
inherits = "release"
opt-level = 3
debug = false
strip = "symbols"
debug-assertions = false
overflow-checks = false
lto = true
panic = "unwind"
incremental = true
codegen-units = 1
rpath = true
