[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

[dependencies]
util = {path = "crates/util"}
gfx  = {path = "crates/gfx"}
log = { version = "0.4.20", features = ["std"]}
rayon = "1.8.1"
# nalgebra-glm = {version = "0.18.0", features = ["convert-bytemuck"] }
# nalgebra = "0.32.3"

[profile.dev]
opt-level = 2
