[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log = { version = "0.4.20", features = ["std"]}
winit = "0.29"
wgpu = "0.19"
bevy_ecs = { version = "0.12.1", features = ["multi-threaded"]}
pollster = "0.3.0"
bytemuck = { version = "1.14.1", features = [ "derive" ] }
cgmath = "0.18.0"
