workspace = { members = [ "crates/game","crates/world_gen"] }
[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

[dependencies]
util = {path = "crates/util"}
gfx  = {path = "crates/gfx"}
world_gen = {path = "crates/world_gen"}
game = {path = "crates/game"}
log = { version = "0.4.20", features = ["std"]}

[profile.dev]
opt-level = 2
