[package]
name = "patinac"
version = "0.0.0-0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.31"
log = { version = "0.4.20", features = ["std"]}
winit = "0.29"
wgpu = "0.19"
pollster = "0.3.0"
bytemuck = { version = "1.14.1", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
strum = {version = "0.26", features = ["derive"] }
nalgebra-glm = {version = "0.18.0", features = ["convert-bytemuck"] }
nalgebra = "0.32.3"
atomic_float = "0.1.0"
winit_input_helper = "0.15.3"
random = "0.14.0"
getrandom = "0.2.12"
tobj = "4.0.1"

[profile.dev]
opt-level = 2

[profile.overdrive]
inherits = "release"
opt-level = 3
panic = "unwind"
strip = "symbols"
lto = true
codegen-units = 1
debug = false
rpath = true