brace_style = "AlwaysNextLine"
combine_control_expr = false
control_brace_style = "AlwaysNextLine"
edition = "2021"
enum_discrim_align_threshold = 32
error_on_line_overflow = true
error_on_unformatted = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
hex_literal_case = "Upper"
imports_layout = "HorizontalVertical"
max_width = 100
imports_granularity = "Module"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
single_line_if_else_max_width = 0
struct_field_align_threshold = 32
struct_lit_single_line = false
trailing_comma = "Never"
unstable_features = true
use_field_init_shorthand = false
use_try_shorthand = true
version = "Two"
wrap_comments = true