# [build]
# rustflags = ["-Zsanitizer=address"]
# target = ["aarch64-apple-darwin"]
# # target = ["x86_64-pc-windows-msvc"]

# [unstable]
# build-std = ["core", "std", "alloc", "test", "proc_macro"]
# build-std-features = ["backtrace", "panic-unwind"]
