# [build]
# rustflags = [-Zsanitizer=thread"]
# target = ["aarch64-apple-darwin"]

# [unstable]
# build-std = ["core", "std", "alloc", "test", "proc_macro"]
# build-std-features = ["backtrace", "panic-unwind"]
