[package]
name = "gfx"
version = "0.1.0"
edition = "2021"

[dependencies]
log = { version = "0.4.20", features = ["std"]}
winit = "0.29"
wgpu = "0.19"
bytemuck = { version = "1.14.1", features = [ "derive" ] }
image = { version = "0.24", default-features = false, features = ["png", "jpeg"] }
strum = {version = "0.26", features = ["derive"] }
nalgebra-glm = {version = "0.18.0", features = ["convert-bytemuck"] }
nalgebra = "0.32.3"
pollster = "0.3.0"
tobj = "4.0.1"
rayon = "1.8.1"
winit_input_helper = "0.15.3"
util = {path = "../util" }