[package]
name = "game"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gfx = { workspace = true }
util = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
oneshot = { workspace = true }
